### ISSUE TITLE
`error_as_node` param used in README example doesn't exist

### ISSUE THREAD

**Issue by smheidrich** [wenkokke/py-tree-sitter-type-provider#94]
The README's example snippet contains 

```python
tstp.TreeSitterTypeProvider(
    "tree_sitter_javascript",
    node_types,
    error_as_node=True,          # Include ERROR as a node in the AST
    as_class_name=as_class_name, # How to convert node types to Python class names
    extra=["comment"],           # Nodes which are marked as 'extra' in the grammar
)
```

But `error_as_node` doesn't seem to exist (anymore) as a `TreeSitterTypeProvider` constructor parameter:

https://github.com/wenkokke/py-tree-sitter-type-provider/blob/38ffa6de375f4775ad9caa9b916490d4f7ad066c/src/tree_sitter_type_provider/__init__.py#L247-L256

**Comment by wenkokke** [comment]
Woops. I think having errors as nodes is the only supported behavior now, since this is how tree sitter parsers work.

The code on line 277 adds an ERROR node unconditionally. The parsing functions take a "raise parse error" parameter instead now.
